cmake_minimum_required(VERSION 3.10.0)
project(oRatioLib VERSION 0.3.0 LANGUAGES CXX)

include(CTest)
enable_testing()

set(BUILD_LISTENERS ON CACHE BOOL "Builds oRatio listeners" FORCE)

option(CHECK_INCONSISTENCIES "Check inconsistencies at each step" OFF)

set(CONSTRAINT_REASONER_TYPES Z3 SeMiTONE)
set(CONSTRAINT_REASONER_TYPE Z3 CACHE STRING "Constraint reasoner type")
set_property(CACHE CONSTRAINT_REASONER_TYPE PROPERTY STRINGS ${CONSTRAINT_REASONER_TYPES})
list(FIND CONSTRAINT_REASONER_TYPES ${CONSTRAINT_REASONER_TYPE} CONSTRAINT_REASONER_TYPE_INDEX)
if(${CONSTRAINT_REASONER_TYPE_INDEX} EQUAL -1)
    message(FATAL_ERROR "Invalid constraint reasoner type ${CONSTRAINT_REASONER_TYPE}")
endif()
message(STATUS "Constraint reasoner type: ${CONSTRAINT_REASONER_TYPE}")

set(TEMPORAL_NETWORK_TYPES LRA DL)
set(TEMPORAL_NETWORK_TYPE LRA CACHE STRING "Temporal network type")
set_property(CACHE TEMPORAL_NETWORK_TYPE PROPERTY STRINGS ${TEMPORAL_NETWORK_TYPES})
list(FIND TEMPORAL_NETWORK_TYPES ${TEMPORAL_NETWORK_TYPE} TEMPORAL_NETWORK_TYPE_INDEX)
if(${TEMPORAL_NETWORK_TYPE_INDEX} EQUAL -1)
    message(FATAL_ERROR "Invalid temporal network type ${TEMPORAL_NETWORK_TYPE}")
endif()
message(STATUS "Temporal network type: ${TEMPORAL_NETWORK_TYPE}")

set(HEURISTIC_TYPES h_max h_add)
set(HEURISTIC_TYPE h_max CACHE STRING "Heuristic type")
set_property(CACHE HEURISTIC_TYPE PROPERTY STRINGS ${HEURISTIC_TYPES})
list(FIND HEURISTIC_TYPES ${HEURISTIC_TYPE} HEURISTIC_TYPE_INDEX)
if(${HEURISTIC_TYPE_INDEX} EQUAL -1)
    message(FATAL_ERROR "Invalid heuristic type ${HEURISTIC_TYPE}")
endif()
message(STATUS "Heuristic type: ${HEURISTIC_TYPE}")

add_subdirectory(extern/riddle)

add_library(oRatioLib src/graph.cpp)
target_compile_features(oRatioLib PUBLIC cxx_std_17)
add_dependencies(oRatioLib RiDDLe)
target_link_libraries(oRatioLib PUBLIC RiDDLe)
target_include_directories(oRatioLib PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>)

if(${CONSTRAINT_REASONER_TYPE} STREQUAL "Z3")
    include(FetchContent)
    FetchContent_Declare(z3 GIT_REPOSITORY https://github.com/Z3Prover/z3 GIT_TAG z3-4.13.4)
    FetchContent_MakeAvailable(z3)

    target_include_directories(oRatioLib PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/z3> ${z3_SOURCE_DIR}/src/api)
    target_sources(oRatioLib PRIVATE src/z3/z3solver.cpp src/z3/z3flaws.cpp src/z3/z3types.cpp)
    target_link_libraries(oRatioLib PUBLIC libz3)
    target_compile_definitions(oRatioLib PUBLIC Z3)
elseif(${CONSTRAINT_REASONER_TYPE} STREQUAL "SeMiTONE")
    target_compile_definitions(oRatioLib PUBLIC SEMITONE)
endif()

if(${HEURISTIC_TYPE} STREQUAL "h_max")
    target_compile_definitions(oRatioLib PRIVATE H_MAX)
elseif(${HEURISTIC_TYPE} STREQUAL "h_add")
    target_compile_definitions(oRatioLib PRIVATE H_ADD)
endif()

message(STATUS "Check inconsistencies at each step: ${CHECK_INCONSISTENCIES}")
if(CHECK_INCONSISTENCIES)
    target_compile_definitions(oRatioLib PRIVATE CHECK_INCONSISTENCIES)
endif()

message(STATUS "Build oRatio listeners: ${BUILD_LISTENERS}")
if(BUILD_LISTENERS)
    target_compile_definitions(oRatioLib PUBLIC BUILD_LISTENERS)
endif()

if(BUILD_TESTING)
    add_subdirectory(tests)
endif()

if(MSVC)
    target_compile_options(oRatioLib PRIVATE /W4)
else()
    target_compile_options(oRatioLib PRIVATE -Wall -Wextra -Wpedantic -fsanitize=undefined)
    if (ENABLE_COVERAGE)
        if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
            target_compile_options(oRatioLib PRIVATE --coverage)
            target_link_libraries(oRatioLib PUBLIC gcov)
        endif()
    endif()
endif()

set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VERSION ${PROJECT_VERSION})
include(CPack)
