cmake_minimum_required(VERSION 3.21)
project(oRatioLib VERSION 0.3.0 LANGUAGES CXX)

include(CTest)
enable_testing()

option(ORATIO_ENABLE_LISTENERS "Enable listener functionality in oRatio" OFF)
option(ORATIO_BUILD_EXECUTABLE "Build the oRatio executable" ON)
option(ORATIO_BUILD_SERVER "Build the oRatio server" OFF)

set(SOLVER_TYPES basic local_search)
set(SOLVER_TYPE basic CACHE STRING "Solver type")
set_property(CACHE SOLVER_TYPE PROPERTY STRINGS ${SOLVER_TYPES})
list(FIND SOLVER_TYPES ${SOLVER_TYPE} SOLVER_TYPE_INDEX)
if(${SOLVER_TYPE_INDEX} EQUAL -1)
    message(FATAL_ERROR "Invalid solver type ${SOLVER_TYPE}")
endif()

if(ORATIO_BUILD_SERVER)
    option(ORATIO_BUILD_WEB_APP "Build the oRatio web application" OFF)
    set(ORATIO_BUILD_EXECUTABLE ON CACHE BOOL "Build the oRatio executable" FORCE)
    set(ORATIO_ENABLE_LISTENERS ON CACHE BOOL "Enable listener functionality in oRatio" FORCE)
    set(COMPUTE_NAMES ON CACHE BOOL "Compute RiDDLe names" FORCE)
    set(CLIENT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/gui/app/dist CACHE STRING "Client directory")
endif()

message(STATUS "Enable listener functionality in oRatio: ${ORATIO_ENABLE_LISTENERS}")
message(STATUS "Build the oRatio executable: ${ORATIO_BUILD_EXECUTABLE}")
message(STATUS "Build the oRatio server: ${ORATIO_BUILD_SERVER}")
message(STATUS "Solver type: ${SOLVER_TYPE}")
if(ORATIO_BUILD_SERVER)
    message(STATUS "Build the oRatio web application: ${ORATIO_BUILD_WEB_APP}")
    message(STATUS "Client directory: ${CLIENT_DIR}")
endif()

set(UTILS_A_STAR_ENABLE_LISTENERS ON CACHE BOOL "Enable listener callbacks for the A* solver in utils" FORCE)
set(UTILS_A_STAR_ENABLE_NAVIGATION ON CACHE BOOL "Enable navigation hooks for the A* solver in utils" FORCE)

add_subdirectory(extern/riddle)
set(LINSPIRE_ENABLE_LISTENERS ON CACHE BOOL "Enable listener functionality in LinSpire" FORCE)
add_subdirectory(extern/linspire)
set(ARCCONSISTENCY_ENABLE_LISTENERS ON CACHE BOOL "Enable listener functionality in ArcConsistency" FORCE)
add_subdirectory(extern/ac)

add_library(oRatioLib src/solver.cpp)
target_compile_features(oRatioLib PUBLIC cxx_std_17)
add_dependencies(oRatioLib RiDDLe LinSpire ArcConsistency)
target_link_libraries(oRatioLib PUBLIC RiDDLe LinSpire ArcConsistency)
target_include_directories(oRatioLib PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include> $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}>)

if(ORATIO_ENABLE_LISTENERS)
    target_compile_definitions(oRatioLib PUBLIC ORATIO_ENABLE_LISTENERS)
endif()

if(${SOLVER_TYPE} STREQUAL "basic")
    target_compile_definitions(oRatioLib PUBLIC BASIC_SOLVER)
    target_sources(oRatioLib PUBLIC src/basic/basic_solver.cpp src/basic/basic_flaws.cpp)
    target_include_directories(oRatioLib PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/basic>)
elseif(${SOLVER_TYPE} STREQUAL "local_search")
    target_compile_definitions(oRatioLib PUBLIC LOCAL_SEARCH_SOLVER)
    target_sources(oRatioLib PUBLIC src/local_search/local_search_solver.cpp src/local_search/local_search_flaws.cpp)
    target_include_directories(oRatioLib PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/local_search>)
endif()

if (ORATIO_BUILD_EXECUTABLE)
    add_executable(oRatio src/main.cpp)
    add_dependencies(oRatio oRatioLib)
    target_link_libraries(oRatio PUBLIC oRatioLib)

    if(ORATIO_BUILD_SERVER)
        target_compile_definitions(oRatio PRIVATE ORATIO_BUILD_SERVER CLIENT_DIR="${CLIENT_DIR}")
        if(${SOLVER_TYPE} STREQUAL "basic")
            target_sources(oRatio PRIVATE src/basic/server/basic_server.cpp)
            target_include_directories(oRatio PRIVATE $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/basic/server>)
        elseif(${SOLVER_TYPE} STREQUAL "local_search")
            target_sources(oRatio PRIVATE src/local_search/server/local_search_server.cpp)
            target_include_directories(oRatio PRIVATE $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/local_search/server>)
        endif()
        if(NOT TARGET ratioNet)
            add_subdirectory(extern/rationet)
        endif()
        add_dependencies(oRatio ratioNet)
        target_link_libraries(oRatio PUBLIC ratioNet)

        add_custom_target(npm_solver_install ALL COMMAND npm install WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/gui/solver COMMENT "Installing the oRatio Solver library" VERBATIM)
        add_custom_target(npm_solver_build ALL COMMAND npm run build WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/gui/solver COMMENT "Building the oRatio Solver library" VERBATIM DEPENDS npm_solver_install)
        if(BUILD_WEB_APP)
            add_custom_target(npm_app_install ALL COMMAND npm install WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/gui/app COMMENT "Installing the oRatio WebApp" VERBATIM DEPENDS npm_solver_build)
            add_custom_target(npm_app_build ALL COMMAND npm run build WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/gui/app COMMENT "Building the oRatio WebApp" VERBATIM DEPENDS npm_app_install)
        endif()
    endif()

    setup_sanitizers(oRatio)
endif()

setup_sanitizers(oRatioLib)

if(BUILD_TESTING)
    add_subdirectory(tests)
endif()

set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VERSION ${PROJECT_VERSION})
include(CPack)
