add_executable(core_tests test_core.cpp)
add_dependencies(core_tests oRatioLib)
target_link_libraries(core_tests PRIVATE oRatioLib)
if(MSVC)
    target_compile_options(core_tests PRIVATE /W4)
else()
    target_compile_options(core_tests PRIVATE -Wall -Wextra -Wpedantic -fsanitize=undefined)
    target_link_options(core_tests PRIVATE -fsanitize=undefined)
    if (ENABLE_COVERAGE)
        if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
            target_compile_options(core_tests PRIVATE --coverage)
            target_link_libraries(core_tests PUBLIC gcov)
        endif()
    endif()
endif()

add_executable(solver_tests test_solver.cpp)
add_dependencies(solver_tests oRatioLib)
target_compile_definitions(solver_tests PRIVATE NUM_TESTS=1)
target_link_libraries(solver_tests PRIVATE oRatioLib)
if(MSVC)
    target_compile_options(solver_tests PRIVATE /W4)
else()
    target_compile_options(solver_tests PRIVATE -Wall -Wextra -Wpedantic -fsanitize=undefined)
    target_link_options(solver_tests PRIVATE -fsanitize=undefined)
    if (ENABLE_COVERAGE)
        if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
            target_compile_options(solver_tests PRIVATE --coverage)
            target_link_libraries(solver_tests PUBLIC gcov)
        endif()
    endif()
endif()

add_test(NAME oRatio_CoreTest COMMAND core_tests WORKING_DIRECTORY ${CMAKE_BINARY_DIR})

add_test(NAME SolverTest00 COMMAND solver_tests "${PROJECT_SOURCE_DIR}/extern/riddle/examples/core/example_00.rddl" "solution.json")
add_test(NAME SolverTest01 COMMAND solver_tests "${PROJECT_SOURCE_DIR}/extern/riddle/examples/core/example_01.rddl" "solution.json")
add_test(NAME SolverTest02 COMMAND solver_tests "${PROJECT_SOURCE_DIR}/extern/riddle/examples/core/example_02.rddl" "solution.json")
set_tests_properties(SolverTest02 PROPERTIES WILL_FAIL TRUE)
