name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]
        #temporal_network: [LA, DL]
        #heuristic_type: [h_max, h_add]
        #deferrable_flaws: [ON, OFF]
        #graph_pruning: [ON, OFF]
        graph_refining: [ON, OFF]
        #check_inconsistencies: [ON, OFF]
        #build_listeners: [ON, OFF]

    env:
      BUILD_TYPE: ${{ matrix.build_type }}
      #TEMPORAL_NETWORK_TYPE: ${{ matrix.temporal_network }}
      #HEURISTIC_TYPE: ${{ matrix.heuristic_type }}
      #DEFERRABLE_FLAWS: ${{ matrix.deferrable_flaws }}
      #GRAPH_PRUNING: ${{ matrix.graph_pruning }}
      GRAPH_REFINING: ${{ matrix.graph_refining }}
      #CHECK_INCONSISTENCIES: ${{ matrix.check_inconsistencies }}
      #BUILD_LISTENERS: ${{ matrix.build_listeners }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DGRAPH_REFINING=${{env.GRAPH_REFINING}} #-DTEMPORAL_NETWORK_TYPE=${{env.TEMPORAL_NETWORK_TYPE}} -DHEURISTIC_TYPE=${{env.HEURISTIC_TYPE}} -DDEFERRABLE_FLAWS=${{env.DEFERRABLE_FLAWS}} -DGRAPH_PRUNING=${{env.GRAPH_PRUNING}} -DCHECK_INCONSISTENCIES=${{env.CHECK_INCONSISTENCIES}} -DBUILD_LISTENERS=${{env.BUILD_LISTENERS}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure --repeat until-pass:10
